apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magento
  template:
    metadata:
      labels:
        app: magento
    spec:
      containers:
        - name: magento-container
          image: docker-image
          imagePullPolicy: Always
          ports:
            - containerPort: 80
 ---
apiVersion: v1
kind: Service
metadata:
  name: magento-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: magento
